version: "3"
services:
  server:
    build: .
    restart: always
    ports:
      - 8888:8888
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "bio-tracking"
      POSTGRES_USER: "dbadmin"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
